require:
  - rubocop-performance
  - rubocop-rspec

#################### Layout ####################

Layout/LineLength:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

#################### Lint ####################

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

#################### Style ####################

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

#################### Metrics ####################

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

#################### RSpec ####################

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

#################### NewRules ##################

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
