name: Gem

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  rubocop-rspec:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.6.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.6

    - name: Cache vendor/bundle
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ env.cache-version }}-${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ env.cache-version }}-${{ runner.os }}-gem-

    - name: Gem install
      env:
        LANG: ja_JP.UTF-8
      run: |
        gem update --system && gem install --no-document bundler:2.1.4
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3

    - name: Run rubocop
      run: bundle exec rubocop

    - name: Run rspec
      run: bundle exec rspec
