name: Rspec

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.6.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.6

    - name: Build and test with Rspec
      run: |
        gem install bundler -v 2.1.4
        bundle install --jobs 4 --retry 3
        bundle exec rspec
